### ISSUE TITLE
Implement IR nodes needed the most

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/sigma-rust#117]
The following IR nodes should be implemented in the interpreter first: 
- [x] SELF #143 
- [x] OUTPUTS #143 
- [x] CONTEXT.dataInputs #143 
- [x] register access (ExtractRegisterAs) #157
- [x] Option.get #149 
- [x] arithmetic ops (plus, minus, multiplication, division)
- [x] tuple access #148 #173

Collection ops: 
- [x] apply 
- [x] size, 
- [x] filter; 
- [x] fold #158

Comparison: 
- [x] NEQ, EQ #150
- [x] GE, LE, GT, LT 

Box properties:
- [x] value #173;
- [x] tokens;
- [x] propositionBytes;

Other:
- [x] OR, BinOr
- [x] AND, BinAnd
- [x] NOT
- [x] IF
- [x] MIN
- [x] MAX
- [x] BLOCK #171
- [x] def (function definition) #159
- [x] APPLY (function application) #171
- [x] blake2b256 #179 
- [x] BoolToSigmaProp
