### ISSUE TITLE
Plan SPV node API

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/sigma-rust#475]
## Goal

To prove that the payment was made, i.e. transaction with a given id is included in the blockchain without downloading all blockchain headers starting from the genesis block. 

## Implementation details
From page 24 of [KMZ17] Non-Interactive Proofs of Proof-of-Work, FC 20 (published) version https://fc20.ifca.ai/preproceedings/74.pdf :
"When a peer informs the client about a payment, they include a
block index `e` and NIPoPoW proof of transaction inclusion. The peer must
then query all of their connected peers, requesting any better proof for the
same predicate. After waiting a short time period for a response, the client
runs the verify-infix (Algorithm 7, p. 20) routine on all received proofs, and accepts the
transaction if the output is true. Although initially, such proofs must be
relative to genesis, the client may store the most recently-known (k-stable)
blockhash for each coin such that future payments can include NIPoPoW
proofs relative to that."

### NIPoPoW
On ergo node side the Algorithm 5 (The Prove algorithm for infix proofs) should be implemented (page 18 of [KMZ17] Non-Interactive Proofs of Proof-of-Work, FC 20 (published) version https://fc20.ifca.ai/preproceedings/74.pdf ).
On sigma-rust side the Algorithm 7 (The verify algorithm for the NIPoPoW infix protocol) should be implemented (page 20 of [KMZ17] Non-Interactive Proofs of Proof-of-Work, FC 20 (published) version https://fc20.ifca.ai/preproceedings/74.pdf )

### P2P networking
We need to be able to query all the connected peers requesting proof for a given predicate (tx id inclusion). The minimum we need:
- connect to a predefined(hardcoded) list of peers;
- request a NIPoPoW proof generated by Algorithm 5 (see above);
- request a block by id from a peer;

Nice to have:
- peer discovery;

### Misc
Parse the block with verified NIPoPoW proof that was received from the peer and check that a tx with a given id is present. Return outputs generated by this tx to the user.

### Todo
- [x] plan p2p networking Implementation https://github.com/ergoplatform/sigma-rust/milestone/17
- [x] plan missing NIPoPoW implementation (Algo 5, see above) for ergo node https://github.com/ergoplatform/ergo/issues/1510;
- [x] plan NIPoPoW implementation (Algo 7, see above) here (separate crate?) https://github.com/ergoplatform/sigma-rust/issues/491 ;

EDIT: progress is tracked in https://github.com/ergoplatform/sigma-rust/milestone/17

**Comment by greenhat** [comment]
@kushti Regarding P2P networking and how to request a block by id. I found `RequestModifierSpec` but the comment says it's not suitable for requesting arbitrary data:
https://github.com/ergoplatform/ergo/blob/95139ec990fc91f8f4c70a61468edf8834143329/src/main/scala/scorex/core/network/message/BasicMessagesRepo.scala#L95-L99
Although SPV node would probably ask for a "recent" block/tx so that might be ok. What do you think?

**Comment by kushti** [comment]
> @kushti Regarding P2P networking and how to request a block by id. I found `RequestModifierSpec` but the comment says it's not suitable for requesting arbitrary data: https://github.com/ergoplatform/ergo/blob/95139ec990fc91f8f4c70a61468edf8834143329/src/main/scala/scorex/core/network/message/BasicMessagesRepo.scala#L95-L99 Although SPV node would probably ask for a "recent" block/tx so that might be ok. What do you think?

The comment says that a node can not deliver certain block (and unconfirmed transactions), if they are not stored there, e.g. in case of light node. A node is providing info on operating regime during handshake, so you can choose with no pruning (or even nodes with pruning and suitable suffix to store, as info on suffix length is also provided).

**Comment by kushti** [comment]
Nipopow proofs now can be obtained in JSON via node API only, we're working on binary serialization and p2p messages

**Comment by greenhat** [comment]
I created a repo for P2P networking library - https://github.com/ergoplatform/ergo-p2p

**Comment by greenhat** [comment]
Progress is tracked in https://github.com/ergoplatform/sigma-rust/milestone/17
